//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowe_robert_SoftwareII_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.cities = new HashSet<city>();
        }
    
        public int countryId { get; set; }
        public string country1 { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public string lastUpdateBy { get; set; }
    
        public virtual ICollection<city> cities { get; set; }
    }
}
